//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPal.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Color_Unknown {
            get {
                return ResourceManager.GetString("Color_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ↳ Exponent.
        /// </summary>
        public static string Editor_Label_ArrowExponent {
            get {
                return ResourceManager.GetString("Editor_Label_ArrowExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Hue.
        /// </summary>
        public static string Editor_Label_Base_Hue {
            get {
                return ResourceManager.GetString("Editor_Label_Base_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Sat.
        /// </summary>
        public static string Editor_Label_Base_Sat {
            get {
                return ResourceManager.GetString("Editor_Label_Base_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Count.
        /// </summary>
        public static string Editor_Label_Color_Count {
            get {
                return ResourceManager.GetString("Editor_Label_Color_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Shift.
        /// </summary>
        public static string Editor_Label_Hue_Shift {
            get {
                return ResourceManager.GetString("Editor_Label_Hue_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Shift Exp.
        /// </summary>
        public static string Editor_Label_Hue_Shift_Exp {
            get {
                return ResourceManager.GetString("Editor_Label_Hue_Shift_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat Shift.
        /// </summary>
        public static string Editor_Label_Sat_Shift {
            get {
                return ResourceManager.GetString("Editor_Label_Sat_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat Shift Exp.
        /// </summary>
        public static string Editor_Label_Sat_Shift_Exp {
            get {
                return ResourceManager.GetString("Editor_Label_Sat_Shift_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Range.
        /// </summary>
        public static string Editor_Label_Value_Range {
            get {
                return ResourceManager.GetString("Editor_Label_Value_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize / Maximize.
        /// </summary>
        public static string Editor_MinMaxBtn_Tooltip {
            get {
                return ResourceManager.GetString("Editor_MinMaxBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        public static string Editor_Ramp_Prefix {
            get {
                return ResourceManager.GetString("Editor_Ramp_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ramp.
        /// </summary>
        public static string Editor_RemoveRampBtn_Tooltip {
            get {
                return ResourceManager.GetString("Editor_RemoveRampBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation Shift.
        /// </summary>
        public static string Editor_SaturationBtn_Tooltip {
            get {
                return ResourceManager.GetString("Editor_SaturationBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Andreas Kruschinski.
        /// </summary>
        public static string InfoWindow_Created_By_krush62 {
            get {
                return ResourceManager.GetString("InfoWindow_Created_By_krush62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.gnu.org/licenses/gpl-3.0.html#license-text.
        /// </summary>
        public static string InfoWindow_GPL_Link {
            get {
                return ResourceManager.GetString("InfoWindow_GPL_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under GPLv3.
        /// </summary>
        public static string InfoWindow_Licensed_under_GPLv3 {
            get {
                return ResourceManager.GetString("InfoWindow_Licensed_under_GPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/krush62/KPal.
        /// </summary>
        public static string InfoWindow_Project_Link {
            get {
                return ResourceManager.GetString("InfoWindow_Project_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Sources:.
        /// </summary>
        public static string InfoWindow_Project_Sources {
            get {
                return ResourceManager.GetString("InfoWindow_Project_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2023.
        /// </summary>
        public static string InfoWindow_Year {
            get {
                return ResourceManager.GetString("InfoWindow_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export empy list..
        /// </summary>
        public static string MainWendow_Msg_Cannot_Export_Empty_List {
            get {
                return ResourceManager.GetString("MainWendow_Msg_Cannot_Export_Empty_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file failed.
        /// </summary>
        public static string MainWindow_Error_Exporting_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Error_Exporting_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindow_Error_General_Title {
            get {
                return ResourceManager.GetString("MainWindow_Error_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file failed.
        /// </summary>
        public static string MainWindow_Error_Loading_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Error_Loading_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file failed.
        /// </summary>
        public static string MainWindow_Error_Saving_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Error_Saving_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MainWindow_ExportBtn_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_ExportBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MainWindow_InfoBtn_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_InfoBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Palette.
        /// </summary>
        public static string MainWindow_LoadBtn_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_LoadBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save empy list..
        /// </summary>
        public static string MainWindow_Msg_Cannot_Save_Empty_List {
            get {
                return ResourceManager.GetString("MainWindow_Msg_Cannot_Save_Empty_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard unsaved changes?.
        /// </summary>
        public static string MainWindow_Msg_Discard_Message {
            get {
                return ResourceManager.GetString("MainWindow_Msg_Discard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to quit?.
        /// </summary>
        public static string MainWindow_Msg_Discard_Title {
            get {
                return ResourceManager.GetString("MainWindow_Msg_Discard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Palette.
        /// </summary>
        public static string MainWindow_NewBtn_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_NewBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Color Ramp.
        /// </summary>
        public static string MainWindow_NewRampBtn_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_NewRampBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save / Save As with right click.
        /// </summary>
        public static string MainWindow_SaveBtn_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_SaveBtn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more color ramps!.
        /// </summary>
        public static string MainWindow_Warning_Cannot_Add_Ramp {
            get {
                return ResourceManager.GetString("MainWindow_Warning_Cannot_Add_Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No color list was found!.
        /// </summary>
        public static string MainWindow_Warning_ColorList_Not_Found {
            get {
                return ResourceManager.GetString("MainWindow_Warning_ColorList_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color list path ({0}) was not found..
        /// </summary>
        public static string MainWindow_Warning_ColorPath_Not_Found {
            get {
                return ResourceManager.GetString("MainWindow_Warning_ColorPath_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MainWindow_Warning_General_Title {
            get {
                return ResourceManager.GetString("MainWindow_Warning_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string PaletteColor_Label_Hue {
            get {
                return ResourceManager.GetString("PaletteColor_Label_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string PaletteColor_Label_Sat {
            get {
                return ResourceManager.GetString("PaletteColor_Label_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Val.
        /// </summary>
        public static string PaletteColor_Label_Val {
            get {
                return ResourceManager.GetString("PaletteColor_Label_Val", resourceCulture);
            }
        }
    }
}
